// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	"github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id        int         `orm:"id,primary" json:"id"`        //
	UserName  string      `orm:"user_name"  json:"userName"`  //
	PassWord  string      `orm:"pass_word"  json:"passWord"`  //
	Email     string      `orm:"email"      json:"email"`     //
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` //
}

// FriendLink is the golang structure for table friend_link.
type FriendLink struct {
	Id          int    `orm:"id,primary"  json:"id"`          //
	Title       string `orm:"title"       json:"title"`       //
	Description string `orm:"description" json:"description"` //
	Url         string `orm:"url"         json:"url"`         //
	Type        string `orm:"type"        json:"type"`        //
}
