// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id       uint        `orm:"id,primary" json:"id"`       // 用户ID
	Passport string      `orm:"passport"   json:"passport"` // 用户账号
	Password string      `orm:"password"   json:"password"` // 用户密码
	Nickname string      `orm:"nickname"   json:"nickname"` // 用户昵称
	CreateAt *gtime.Time `orm:"create_at"  json:"createAt"` // 创建时间
	UpdateAt *gtime.Time `orm:"update_at"  json:"updateAt"` // 更新时间
}

// Link is the golang structure for table link.
type Link struct {
	Id        int         `orm:"id,primary" json:"id"`        // ID
	Title     string      `orm:"title"      json:"title"`     // 链接标题
	Url       string      `orm:"url"        json:"url"`       // 链接地址
	Body      string      `orm:"body"       json:"body"`      // 链接描述
	CreatedAt *gtime.Time `orm:"created_at" json:"createdAt"` // 创建时间
}
