// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ArticleForDao is the golang structure of table article for DAO operations like Where/Data.
type Article struct {
	g.Meta    `orm:"dto:true"`
	Id        interface{} // ID
	Local     interface{} // zh 中文 en 英文
	Title     interface{} // 标题
	Body      interface{} // 文章内容
	TypeId    interface{} // 文章分类ID
	Author    interface{} // 作者
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 修改时间
}
