// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
)

// FriendLinkForDao is the golang structure of table friend_link for DAO operations like Where/Data.
type FriendLink struct {
	g.Meta      `orm:"dto:true"`
	Id          interface{} // Id
	Title       interface{} // 标题
	Description interface{} // 描述
	Url         interface{} // 链接地址
	Type        interface{} // 跳转类型
}
