// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserForDao is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta    `orm:"dto:true"`
	Id        interface{} // Id
	UserName  interface{} // 用户名
	PassWord  interface{} // 密码
	Email     interface{} // 邮箱
	CreatedAt *gtime.Time // 注册时间
}
