// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/template-single/internal/service/internal/dao/internal"
)

// friendLinkDao is the data access object for table friend_link.
// You can define custom methods on it to extend its functionality as you wish.
type friendLinkDao struct {
	*internal.FriendLinkDao
}

var (
	// FriendLink is globally public accessible object for table friend_link operations.
	FriendLink = friendLinkDao{
		internal.NewFriendLinkDao(),
	}
)

// Fill with you ideas below.
