# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "gf-app"
	LogPath     = "D:\\Goworks\\src\\enterprise-api\\log\\gf-app\\server"

# Logger.
[logger]
    Path        = "D:\\Goworks\\src\\enterprise-api\\log\\gf-app"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    # Delimiters  =  ["{{", "}}"]

# Database.
[database]
    link  = "mysql:root:root@tcp(127.0.0.1:3306)/eweb"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "D:\\Goworks\\src\\enterprise-api\\log\\gf-app\\sql"
        Level  = "all"
        Stdout = true
# GF-CLI 工具配置
[gfcli]
    # 自定义 DAO 生成配置（默认读取 database 配置）
    [[gfcli.gen.dao]]
        link = "mysql:root:root@tcp(127.0.0.1:3306)/eweb"
        tables = "user,friend_link"