// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"enterprise-api/app/dao/internal"
)

// friendLinkDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type friendLinkDao struct {
	*internal.FriendLinkDao
}

var (
	// FriendLink is globally public accessible object for table friend_link operations.
	FriendLink friendLinkDao
)

func init() {
	FriendLink = friendLinkDao{
		internal.NewFriendLinkDao(),
	}
}

// Fill with you ideas below.
