// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"enterprise-api/app/dao/internal"
)

// linkDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type linkDao struct {
	*internal.LinkDao
}

var (
	// Link is globally public accessible object for table link operations.
	Link linkDao
)

func init() {
	Link = linkDao{
		internal.NewLinkDao(),
	}
}

// Fill with you ideas below.
