// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Article is the golang structure for table article.
type Article struct {
	Id        int         `json:"id"        ` // ID
	Local     string      `json:"local"     ` // zh 中文 en 英文
	Title     string      `json:"title"     ` // 标题
	Body      string      `json:"body"      ` // 文章内容
	TypeId    int         `json:"typeId"    ` // 文章分类ID
	Author    string      `json:"author"    ` // 作者
	CreatedAt *gtime.Time `json:"createdAt" ` // 创建时间
	UpdatedAt *gtime.Time `json:"updatedAt" ` // 修改时间
}
