// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// FriendLink is the golang structure for table friend_link.
type FriendLink struct {
	Id          int    `json:"id"          ` // Id
	Title       string `json:"title"       ` // 标题
	Description string `json:"description" ` // 描述
	Url         string `json:"url"         ` // 链接地址
	Type        string `json:"type"        ` // 跳转类型
}
