// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Migrations is the golang structure for table migrations.
type Migrations struct {
	IdMigration        uint        `json:"idMigration"        ` // surrogate key
	Name               string      `json:"name"               ` // migration name, unique
	CreatedAt          *gtime.Time `json:"createdAt"          ` // date migrated or rolled back
	Statements         string      `json:"statements"         ` // SQL statements for this migration
	RollbackStatements string      `json:"rollbackStatements" ` // SQL statment for rolling back migration
	Status             string      `json:"status"             ` // update indicates it is a normal migration while rollback means this migration is rolled back
}
