// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// FriendLinkDao is the manager for logic model data accessing and custom defined data operations functions management.
type FriendLinkDao struct {
	gmvc.M                   // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      friendLinkColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB            // DB is the raw underlying database management object.
	Table  string            // Table is the underlying table name of the DAO.
}

// FriendLinkColumns defines and stores column names for table friend_link.
type friendLinkColumns struct {
	Id          string // Id
	Title       string // 标题
	Description string // 描述
	Url         string // 链接地址
	Type        string // 跳转类型
}

// NewFriendLinkDao creates and returns a new DAO object for table data access.
func NewFriendLinkDao() *FriendLinkDao {
	columns := friendLinkColumns{
		Id:          "id",
		Title:       "title",
		Description: "description",
		Url:         "url",
		Type:        "type",
	}
	return &FriendLinkDao{
		C:     columns,
		M:     g.DB("default").Model("friend_link").Safe(),
		DB:    g.DB("default"),
		Table: "friend_link",
	}
}
