// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// LinkDao is the manager for logic model data accessing and custom defined data operations functions management.
type LinkDao struct {
	gmvc.M             // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      linkColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB      // DB is the raw underlying database management object.
	Table  string      // Table is the underlying table name of the DAO.
}

// LinkColumns defines and stores column names for table link.
type linkColumns struct {
}

// NewLinkDao creates and returns a new DAO object for table data access.
func NewLinkDao() *LinkDao {
	columns := linkColumns{}
	return &LinkDao{
		C:     columns,
		M:     g.DB("default").Model("link").Safe(),
		DB:    g.DB("default"),
		Table: "link",
	}
}
